### ISSUE TITLE
Support for macos

### ISSUE THREAD

**Issue by spotandjake** [LucidVR/lucidgloves-openvr#211]
I'm running SteamVR on Macos with my Oculus quest, and was wondering if there is any plan to support macos with this driver?

**Comment by hardlite** [comment]
A) Not an issue
B) How is that possible? Valve abandoned Steamvr on macOS years ago, and I don't believe Oculus ever supported it

**Comment by danwillm** [comment]
I don't think we even have the ability to support macos (I'm not sure how you've got it working with Oculus in the first place) - we would have to move the driver back to older interfaces that are compatible with the build for macos steamvr, which isn't really in our interest to do (it would degrade the experience for other users on actually supported platforms).

We have support for linux coming soon, though, as that is a supported platform for steamvr.
