### ISSUE TITLE
Support for trackpad

### ISSUE THREAD

**Issue by blackjacksike** [LucidVR/lucidgloves-openvr#212]
The Valve Index controllers have a trackpad, which is used in games like HL:Alyx to select a weapon. It would be nice if such a feature was supported by opengloves, so that you don't have to setup a gesture to simulate it.

**Comment by danwillm** [comment]
You can use the steamvr bindings to configure the index controller inputs for half life alyx.

Alternatively you can switch to using the lucidgloves device which has these appropriate bindings
