### ISSUE TITLE
Missing/incorrect configuration values cause unpredictable behavior

### ISSUE THREAD

**Issue by WillNilges** [LucidVR/lucidgloves-openvr#217]
I found a bug that would prevent my gloves from working properly and cause Unity to spew errors:

![image](https://user-images.githubusercontent.com/42927786/208552454-83c7ccea-a79e-42e6-b147-67c4d5caf4ee.png)

The cause was that my configuration files didn't have `encoding_alpha` set properly, and thus it was defaulting to zero, causing division by zeros.

I'm making this issue as a reminder that steamvr configuration can be weird, and we might want to add checks to like... everything, so that we see errors in the SteamVR logs if we get something unexpected from the config file.

**Comment by ghost** [comment]
You can add a very small bias to prevent divisions by zero
