### ISSUE TITLE
What should I do if I want to use the 'A', 'B' button and joystick of quest2 handshank instead of the customized one from openglove?

### ISSUE THREAD

**Issue by Radiation-2077** [LucidVR/lucidgloves-openvr#221]
I find that if the openglove driver is applied, it will automatically disables the built in buttons and joystick of the hand shank and enable its own one. I'm wondering if there is a way to enable the buttons of the handshank and disable the one of openglove since I don't want to have any button left on the glove for some reasons.
Is there a way to set some kind of priority level for the input devices that I can choose which set of input buttons I gonna use? Or should I just delete the relevant input part of the driver.

**Comment by danwillm** [comment]
it's not possible in steamvr to have multiple controllers active per hand, which is why you are not able to use your quest 2 controllers when using the gloves.

If you don't want to use the gloves, you can disable them in steamvr settings > startup/shutdown > manage addons.
