### ISSUE TITLE
Wiki - Dead link to haptic event driver sample in "Driver Input"

### ISSUE THREAD

**Issue by ErrorRaffyline0** [LucidVR/lucidgloves-openvr#233]
https://github.com/LucidVR/opengloves-driver/wiki/Driver-Input#driver-outputs

**Comment by danwillm** [comment]
Thanks for spotting. I moved those docs to the Valve OpenVR repo. You can see it here: https://github.com/ValveSoftware/openvr/blob/master/samples/drivers/drivers/simplecontroller/src/controller_device_driver.cpp#L255
