### ISSUE TITLE
[BUG] newest opengloves steam version auto starts index fingertracking emulator when using virtual desktop with handtracking

### ISSUE THREAD

**Issue by The-Wrench** [LucidVR/lucidgloves-openvr#234]
i spent like 8h troublehshooting my steamvr just to find out that for god knows what reason opengloves (the steam edition) randomly decides to start the index finer tracking emulator of the driver without any esp or arduino or anything else being connected. because apparently it recognises the quest 2 handtracking as a lucidglove for god knows what reason.

i can provide logs in nessecary

this isnt really a hardware bug but definetly a software bug

**Comment by danwillm** [comment]
Did you find a solution to your problem?
