### ISSUE TITLE
How do I turn on named pipes

### ISSUE THREAD

**Issue by juan-xin-cai** [LucidVR/lucidgloves-openvr#237]
I looked at the list of all the pipes and did not find the pipe name mentioned in the doc
![image](https://github.com/LucidVR/opengloves-driver/assets/33806107/637bc68d-7b95-402b-bb5e-5c0074b65cbe)
umentation

**Comment by danwillm** [comment]
You need to open the opengloves UI and check the "enable" under the named pipes section.

**Comment by juan-xin-cai** [comment]
Thx，I got it
