### ISSUE TITLE
Does VRChat not support splay?

### ISSUE THREAD

**Issue by juan-xin-cai** [LucidVR/lucidgloves-openvr#239]

**Comment by danwillm** [comment]
Hi, no it doesn't. But the driver exposes splay from osc outputs which you can then use in vrchat avatars.

**Comment by danwillm** [comment]
Hi, no it doesn't. But the driver exposes splay from osc outputs which you can then use in vrchat.

**Comment by juan-xin-cai** [comment]
thx
