### ISSUE TITLE
 I want to implement the mapping of touch button or trackpad of Index

### ISSUE THREAD

**Issue by juan-xin-cai** [LucidVR/lucidgloves-openvr#243]
I want to realize the mapping of the touch button or trackpad of the finger tiger, Is there any corresponding parameter？

**Comment by danwillm** [comment]
I'm not too sure what you're trying to do.
If you're trying to map inputs from touch controllers, I'm afraid this isn't possible and you'll have to look for other solutions to get what you're looking for. If you're looking for something different, feel free to reply and I'll try my best to help.
Thanks!
